route:
  receiver: 'telegram'
  group_by: [ alertname ]

  routes:
    - matchers:
      - severity="critical"
      receiver: 'telegram'
      
    - matchers:
      - severity="warning"
      receiver: 'mail'

receivers:
- name: 'telegram'
  telegram_configs:
    - api_url: https://api.telegram.org
      bot_token: '7013824454:AAHoohhT_Nvszv-Qy6jh7LKzrh3oZXp1rvA'
      send_resolved: true
      chat_id: 6288296528

- name: 'mail'
  email_configs:
  - to: 'mmnt1337@otus.alert'
    from: 'alert@otus.alert'
    smarthost: 'mailhog:1025'
    require_tls: false
